#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

[ "$ACTION" = released ] || exit 0

if [ "$(pgrep poweroff | wc -l)" -ge 4 ]; then
	pkill poweroff
	firstboot -y
	reboot
else
	poweroff -d 5 &
fi
