#!/bin/sh /etc/rc.common
# shellcheck disable=SC2039
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC2034
{
	START=90
	STOP=10
	USE_PROCD=1
}

validate_section() {
	uci_validate_section graph opentsdb "$1" \
		'enable:bool:1'            \
		'url:string'               \
		'freq:uinteger'
}

start_instance() {
	local enable url freq
	validate_section "$1" || return

	[ "$enable" = "0" ] && return
	[ -z "$url" ] && return

	hostname=$(uci -q get system.@system[0].hostname)

	procd_open_instance
	procd_set_param command /bin/graph "$url" "$hostname" "$freq"
	procd_set_param respawn 0 5 0
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load graph
	config_foreach start_instance opentsdb
}

service_triggers() {
	procd_add_reload_trigger graph
}
