#!/bin/sh

. /lib/functions/network.sh

uci -q batch <<EOF
set network.globals.multipath='enable'
EOF

_setup() {
	case "$1" in
	wan*)
		uci -q batch <<-EOF
		set network.$1.multipath=on
		set network.$1.proto=dhcp
		set network.$1.metric=${1#wan}
		add_list firewall.mptcp.network=$1
		EOF
		;;
	none) # hack (see /etc/board.d/02_network)
		uci -q delete "network.$1"
		;;
	*tun*)
		uci -q batch <<-EOF
		set network.$1.multipath=off
		add_list firewall.wan.network=$1
		EOF
		;;
	if*)
		;;
	*)
		uci -q batch <<-EOF
		set network.$1.multipath=off
		EOF
		;;
	esac
}

config_load network
config_foreach _setup interface

uci -q commit network
uci -q commit firewall

exit 0
