#!/bin/sh

touch /etc/config/network

uci -q batch <<EOF
set network.globals=globals
set network.globals.multipath='enable'

set network.loopback=interface
set network.loopback.multipath='off'
set network.loopback.ifname='lo'
set network.loopback.proto='static'
set network.loopback.ipaddr='127.0.0.1'
set network.loopback.netmask='255.0.0.0'

set network.lan=interface
set network.lan.multipath='off'
set network.lan.ifname='eth0'
set network.lan.type='bridge'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.1.1'
set network.lan.netmask='255.255.255.0'

set network.tun0=interface
set network.tun0.multipath='off'
set network.tun0.ifname='tun0'
set network.tun0.proto='static'
set network.tun0.ipaddr='10.166.178.2'
set network.tun0.netmask='255.255.255.0'

commit network
EOF

exit 0
