#!/bin/sh

grep -sq vlan /etc/otb-version || exit 0

uci -q batch <<EOF
set network.lan.ifname='eth0'
set network.lan.type=

set network.switch0=switch
set network.switch0.name='otbv2sw'
set network.switch0.enable_vlan='1'
set network.switch0.reset='1'
EOF

for pt in 13 14; do
	uci -q batch <<-EOF
	set network.wan${pt}=interface
	set network.wan${pt}.multipath='on'
	set network.wan${pt}.ifname='eth0.${pt}'
	set network.wan${pt}.proto='dhcp'
	set network.wan${pt}.metric='${pt}'

	set network.vlan${pt}=switch_vlan
	set network.vlan${pt}.device='otbv2sw'
	set network.vlan${pt}.vlan='${pt}'
	set network.vlan${pt}.ports='${pt} 15t'

	add_list firewall.mptcp.network='wan${pt}'
	EOF
done

uci -q batch <<EOF
set network.vlan100=switch_vlan
set network.vlan100.device='otbv2sw'
set network.vlan100.vlan='100'
set network.vlan100.ports='1 2 3 4 5 6 7 8 9 10 11 12 15 16 17 18'

set network.vlan4004=switch_vlan
set network.vlan4004.device='otbv2sw'
set network.vlan4004.vlan='4004'
set network.vlan4004.ports='15t'

commit network
commit firewall
EOF

exit 0
