#!/bin/sh
# shellcheck disable=SC1090,SC1091

TARGET=mmcblk0

if read -r CMD < /proc/cmdline; then
	case "$CMD" in
		*rootfstype=ubifs*)
			return
			;;
		*recovery=*)
			TARGET="${CMD##*recovery=}"
			TARGET="${TARGET%% *}"
			;;
	esac
fi

# Return if the target does not exist
[ -b /dev/"$TARGET" ] || return

# Get DEVNAME of the boot device
. /lib/upgrade/common.sh
export_bootdevice
. /sys/dev/block/"$BOOTDEV_MAJOR:$BOOTDEV_MINOR"/uevent

# If the boot device is the same as the target, return
[ "$DEVNAME" = "$TARGET" ] && return

# Get the size of the usb filesystem
COUNT=0
for part in /sys/dev/block/"$BOOTDEV_MAJOR:$BOOTDEV_MINOR/$DEVNAME"*; do
	START=$(cat "$part"/start)
	SIZE=$(cat "$part"/size)
	NEWCOUNT=$((START+SIZE))
	[ "$NEWCOUNT" -gt "$COUNT" ] && COUNT=$NEWCOUNT
done
[ "$COUNT" = 0 ] && return

echo "RECOVERY: from $DEVNAME to $TARGET ($COUNT blocks)"
dd if=/dev/"$DEVNAME" of=/dev/"$TARGET" bs=512 count="$COUNT" || return
sync

echo "RECOVERY: done! rebooting..."
sleep 2
reboot -f
