#!/bin/sh

# On V2B ttyS0 is used for the switch

do_inittab() {
	if [ -f /sys/devices/virtual/dmi/id/product_version ]; then
		pv=$(cat /sys/devices/virtual/dmi/id/product_version)
		[ "$pv" = V2B ] && sed -i /ttyS0/d /etc/inittab
	fi
}

boot_hook_add preinit_main do_inittab
