#!/bin/sh

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh

board_config_update

board="$(cat /tmp/sysinfo/board_name)"

case "$board" in
*overthebox-v2b)
	# vlan 1 doesn't work and port 16 is not used so use it for a null role
	ucidef_add_switch "otbv2sw" "15t@eth0" "16:none" \
		"1:lan" "2:lan" "3:lan" "4:lan" "5:lan" "6:lan" \
		"7:lan" "8:lan" "9:lan" "10:lan" "11:lan" "12:lan" \
		"17:lan" "18:lan" "13:wan13" "14:wan14"
	;;
*)
	ucidef_set_interface_lan "eth0"

	ucidef_set_interface_raw "if0" "eth0" "dhcp"
	ucidef_set_interface_macaddr "if0" "auto"
	;;
esac

board_config_flush

exit 0
