#!/bin/sh /etc/rc.common
# shellcheck disable=SC1091
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC2034
{
	START=90
	STOP=10
	USE_PROCD=1
}

boot() {
	. /lib/overthebox
	otb_save_event boot
	start "$@"
}

start_service() {
	procd_open_instance
	procd_set_param command /bin/otb-daemon
	procd_set_param respawn 0 5 0
	procd_set_param term_timeout 600
	procd_set_param stderr 1
	procd_close_instance
}
