#!/bin/sh /etc/rc.common
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

# shellcheck disable=SC2034
{
	START=95
	STOP=5
	USE_PROCD=1
}

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/httpd -f -h /www
	procd_set_param respawn 0 5 0
	procd_set_param term_timeout 600
	procd_set_param stderr 1
	procd_close_instance
}
